"""empty message

Revision ID: bfb8ccfde5b0
Revises: 50f44f0534f2
Create Date: 2021-02-28 10:11:30.381841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb8ccfde5b0'
down_revision = '50f44f0534f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('difficulty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'difficulty')
    # ### end Alembic commands ###
